### PR TITLE
Fix #2540 Ejabberd doesnt compile as mix umbrella project dependency

### LINKED ISSUE #2540: Ejabberd doesn't compile as mix umbrella project dependency
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Elixir docker image

> How did you install ejabberd (source, package, distribution)?

hex package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have created basic mix umbrella project [https://github.com/pdorofiejczyk/elixir_umbrella_hello_world](https://github.com/pdorofiejczyk/elixir_umbrella_hello_world). It contains one elixir application which have ejabberd as dependendency. When I'm trying to compile, I'm getting error ```src/mod_muc_log.erl:47: can't find include file "xmpp.hrl"```. Everything works fine if it is not umbrella project.

### PR DESCRIPTION
**Pull request by pdorofiejczyk**
This PR fixes #2540. It is not perfect way but it works for most of cases. The problem remains when given project has custom ```deps_path``` configuration but as I know there is no way to get this config option from dependencie's ```mix.exs``` level.

### CODE REVIEW

File: mix.exs [hunk 1]
```diff
@@ -96,9 +96,13 @@ defmodule Ejabberd.Mixfile do
   end
 
   defp deps_include(deps) do
-    base = case Mix.Project.deps_paths()[:ejabberd] do
-      nil -> "deps"
-      _ -> ".."
+    base = if Mix.Project.umbrella?() do
```
Comment (fabiankrol) [inline mix.exs]: 👏

**Comment by mremond** [comment]
Many thanks for the patch!
