### PR TITLE
don't crash in get_invite_by_invitee_t for sql backend

### LINKED ISSUE #4565: Crash in mod_invites when more then one invite for invitee.
Ejabberd 26.03 crashes when creating new token (ad-hoc create-account):

```log
2026-04-11 15:31:38.663635+03:00 [error] <0.41565.0>@ejabberd_hooks:safe_apply/4:460 Hook adhoc_local_commands crashed when running mod_invites:adhoc_commands/4:
** exception error: no function clause matching
                  mod_invites:reason_to_text({case_clause,
                                              {selected,
                                               [{<<"token1">>,
                                                 <<>>,
                                                 <<"countnazgul@XXX.org">>,
                                                 <<"A">>,<<>>,
                                                 {{2026,1,29},{6,20,20}},
                                                 {{2026,1,26},{6,20,20}}},
                                                {<<"token2">>,
                                                 <<"mi6">>,
                                                 <<"countnazgul@XXX.org">>,
                                                 <<"R">>,<<>>,
                                                 {{2026,1,29},{10,27,5}},
                                                 {{2026,1,26},{10,27,5}}}]}}) (src/mod_invites.erl:1145)
   in function  mod_invites:to_stanza_error/2 (src/mod_invites.erl:1142)
   in call from mod_invites:'-adhoc_commands/4-fun-1-'/6 (src/mod_invites.erl:574)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl:456)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl:403)
   in call from mod_adhoc:process_adhoc_request/2 (src/mod_adhoc.erl:187)
   in call from gen_iq_handler:process_iq/3 (src/gen_iq_handler.erl:131)
   in call from gen_iq_handler:process_iq/4 (src/gen_iq_handler.erl:109)
** Arg 1 = empty
** Arg 2 = {jid,<<"countnazgul">>,<<"XXX.org">>,
                <<"Conversations.-k9i65zoHu">>,<<"countnazgul">>,
                <<"XXX.org">>,<<"Conversations.-k9i65zoHu">>}
** Arg 3 = {jid,<<>>,<<"XXX.org">>,<<>>,<<>>,<<"XXX.org">>,<<>>}
** Arg 4 = {adhoc_command,<<"urn:xmpp:invite#create-account">>,execute,
               <<"gaSEf7NmLIIZb4s9tiTzAAcv">>,undefined,<<"en">>,undefined,[],
               {xdata,submit,[],undefined,undefined,[],
                   [{xdata_field,<<>>,undefined,<<"roster-subscription">>,
                        false,<<>>,
                        [<<"1">>],
                        [],[]}]}}
2026-04-11 15:31:50.540560+03:00 [error] <0.41565.0>@ejabberd_hooks:safe_apply/4:460 Hook adhoc_local_commands crashed when running mod_invites:adhoc_commands/4:
** exception error: no function clause matching
                  mod_invites:reason_to_text({case_clause,
                                              {selected,
                                               [{<<"token1">>,
                                                 <<>>,
                                                 <<"countnazgul@XXX.org">>,
                                                 <<"A">>,<<>>,
                                                 {{2026,1,29},{6,20,20}},
                                                 {{2026,1,26},{6,20,20}}},
                                                {<<"token2">>,
                                                 <<"mi6">>,
                                                 <<"countnazgul@XXX.org">>,
                                                 <<"R">>,<<>>,
                                                 {{2026,1,29},{10,27,5}},
                                                 {{2026,1,26},{10,27,5}}}]}}) (src/mod_invites.erl:1145)
   in function  mod_invites:to_stanza_error/2 (src/mod_invites.erl:1142)
   in call from mod_invites:'-adhoc_commands/4-fun-1-'/6 (src/mod_invites.erl:574)
   in call from ejabberd_hooks:safe_apply/4 (src/ejabberd_hooks.erl:456)
   in call from ejabberd_hooks:run_fold1/4 (src/ejabberd_hooks.erl:403)
   in call from mod_adhoc:process_adhoc_request/2 (src/mod_adhoc.erl:187)
   in call from gen_iq_handler:process_iq/3 (src/gen_iq_handler.erl:131)
   in call from gen_iq_handler:process_iq/4 (src/gen_iq_handler.erl:109)
** Arg 1 = empty
** Arg 2 = {jid,<<"countnazgul">>,<<"XXX.org">>,
                <<"Conversations.-k9i65zoHu">>,<<"countnazgul">>,
                <<"XXX.org">>,<<"Conversations.-k9i65zoHu">>}
** Arg 3 = {jid,<<>>,<<"XXX.org">>,<<>>,<<>>,<<"XXX.org">>,<<>>}
** Arg 4 = {adhoc_command,<<"urn:xmpp:invite#create-account">>,execute,
               <<"XKHTHPJFu9VqzgxaJtuUgy6Y">>,undefined,<<"en">>,undefined,[],
               {xdata,submit,[],undefined,undefined,[],
                   [{xdata_field,<<>>,undefined,<<"roster-subscription">>,
                        false,<<>>,
                        [<<"1">>],
                        [],[]}]}}
```

### PR DESCRIPTION
**Pull request by sstrigler**
There was a missing where clause for the type of the invite.

Furthermore we need to check roster_only invites if they have been used for creating the account - here it can happen invitee is not being set (yet).

Fixes #4565

### CODE REVIEW

File: src/mod_invites_mnesia.erl [hunk 1]
```diff
@@ -88,7 +96,7 @@ init(_Host, _Opts) ->
                            invite_token,
                            [{disc_copies, [node()]},
                             {attributes, record_info(fields, invite_token)},
-                            {index, [inviter, invitee]}]).
+                            {index, [inviter, invitee, account_name]}]).
```
Comment (sstrigler) [inline src/mod_invites_mnesia.erl:99]: How do you migrate an mnesia schema?

Comment (sstrigler) [reply src/mod_invites_mnesia.erl:99]: Seems this works automagically?

Comment (sstrigler) [reply src/mod_invites_mnesia.erl:99]: Nvm, found the code. Wasn't that hard to find actually. 🫣
